### ISSUE TITLE
Add cargo.lock file?

### ISSUE THREAD

**Issue by byrongibson** [MeadowlarkDAW/Meadowlark#27]
Hello, cool project!  Any chance you guys can include a cargo.lock file?  It's needed to package it [in NixOS](https://github.com/NixOS/nixpkgs/issues/144565#issuecomment-976130608).

**Comment by BillyDM** [comment]
Oh, uhh, Meadowlark is still in the early stages of development and is in no way ready to be packaged. There is hardly even any GUI yet, most of the work done so far has been in the backend.

We'll definitely help with packaging Meadowlark on different platforms once it's ready for an alpha/beta release.
