### ISSUE TITLE
CI for building and releasing meadowlark on each commit

### ISSUE THREAD

**Issue by dragonDScript** [MeadowlarkDAW/Meadowlark#52]
I can do this myself (I want to). Should I do it? any inconveniences?

**Comment by BillyDM** [comment]
When the time comes to actually release builds of Meadowlark, then sure. That's still months away though.

**Comment by dragonDScript** [comment]
This is so that people can download each release of meadowlark without doing the mess of downloading git, setting up github account, cloning, downloading rust, compile, "there's an error, why?", ...

**Comment by BillyDM** [comment]
Once we're actually ready for people to test things, then we'll add it. As of right now, there is barely even an app for people to test. It may be a couple of months or so until it's "usable".

**Comment by dragonDScript** [comment]
OK
