### ISSUE TITLE
Expected usize

### ISSUE THREAD

**Issue by antonovmike** [MeadowlarkDAW/Meadowlark#55]
Doesn't run because compiler complains about the isize:

Meadowlark/src/backend/sample_browser_plug.rs

line 336
`pcm.fill_stereo_f32(playhead as isize, buf_l_part, buf_r_part);`
line 369
`old_playhead as isize,`

Changed to usize. Now DAW starts

**Comment by BillyDM** [comment]
Currently only the `dev` branch is working. Also make sure to run `cargo update` first as this problem is usually caused by dependencies being updated.
