### ISSUE TITLE
Github actions failing

### ISSUE THREAD

**Issue by darless** [MeadowlarkDAW/Meadowlark#61]
Github actions shows failures. Pull requests and straight commits should not be allowed if the actions are failing. For this issue:

- [ ] Fix all github action failures
- [ ] Update repository settings to prevent a pull request being merged in if github actions CI fail to run

Current failures from commit: https://github.com/MeadowlarkDAW/Meadowlark/commit/8c94a41d7c140cf3fd7e2f03a45cc4b1d6543036

[check](https://github.com/MeadowlarkDAW/Meadowlark/actions/runs/3925984855/jobs/6711288560)
```
  error: could not compile `meadowlark` due to 3 previous errors; 95 warnings emitted
  {"reason":"build-finished","success":false}
Clippy results: 0 ICE, 2 errors, 95 warnings, 0 notes, 0 help
Error: Clippy had exited with the 101 exit code
```

[miri - Memory Leak](https://github.com/MeadowlarkDAW/Meadowlark/actions/runs/3925984855/jobs/6711288356
)```
error: the evaluated program leaked memory
Error: the evaluated program leaked memory
note: pass `-Zmiri-ignore-leaks` to disable this check

error: aborting due to previous error; 3 warnings emitted
Error: aborting due to previous error; 3 warnings emitted
error: test failed, to rerun pass `-p meadowlark --bin meadowlark`

Caused by:
  process didn't exit successfully: `/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri runner /home/runner/work/Meadowlark/Meadowlark/target/miri/x86_64-unknown-linux-gnu/ci/deps/meadowlark-c20dddbb7b88e334` (exit status: 1)
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 1
```

[clippy](https://github.com/MeadowlarkDAW/Meadowlark/runs/10662656321)
```
Executing cargo clippy (JSON output)
Clippy results: 0 ICE, 2 errors, 95 warnings, 0 notes, 0 help
Error: Clippy had exited with the 101 exit code
```

**Comment by BillyDM** [comment]
Oh right, I'll get to that at some point. But until Meadowlark has its first alpha release, I don't really see a problem committing to main in its current state.

The reason I recently pushed the contents of dev to main in the first place was because I was getting issues about the main branch not building at all.

**Comment by BillyDM** [comment]
closing because of a rewrite
