### ISSUE TITLE
add image to readme

### ISSUE THREAD

**Issue by RustoMCSpit** [MeadowlarkDAW/Meadowlark#65]

**Comment by BillyDM** [comment]
I'm waiting until I have a working prototype to show before adding an image to the readme. I've had too many people asking how to build and run the project when there wasn't really anything to show.

**Comment by RustoMCSpit** [comment]
> I'm waiting until I have a working prototype to show before adding an image to the readme. I've had too many people asking how to build and run the project when there wasn't really anything to show.

when will that be roughly?
